package refractor_test

// corpusBranchVerdicts pins every executable cypher the installed corpus ships.
// Nineteen lenses decompose; every other row records a cypher this mechanism
// leaves on the product path, which is the half of the census an eye-reading
// gets wrong.
var corpusBranchVerdicts = map[string]branchVerdict{
	"applicantRosterRead":            {"g0/o0!no-aggregating-item", 0, 0},
	"appointmentReminders":           {"g2/o2!no-aggregating-item", 0, 2},
	"augurDispatchPending":           {"g0/o0!no-aggregating-item", 0, 0},
	"augurProposals":                 {"g0/o0!no-aggregating-item", 0, 0},
	"availableListings":              {"g0/o0!no-aggregating-item", 0, 0},
	"backgroundCheckFreshness":       {"g0/o0!no-aggregating-item g0/o0!no-aggregating-item", 0, 0},
	"cafeIdentitiesRead":             {"g0/o0!no-aggregating-item", 0, 0},
	"cafeLeaseAccounts":              {"g1/o1!no-aggregating-item", 0, 1},
	"cafeLeaseWorkplaces":            {"g1/o1!no-aggregating-item", 0, 1},
	"cafeLedgerHistory":              {"g0/o0!no-aggregating-item", 0, 0},
	"cafeStaleTabSettlement":         {"g0/o0!no-aggregating-item", 0, 0},
	"cafeTabSettlement":              {"g3/o3!multiplicity-sensitive-aggregator g0/o0!no-aggregating-item g0/o0!no-aggregating-item", 0, 3},
	"capability":                     {"g0/o0!no-aggregating-item", 0, 0},
	"capabilityAuthorContext":        {"g0/o0!no-aggregating-item", 0, 0},
	"capabilityAuthorPackages":       {"g0/o0!no-aggregating-item", 0, 0},
	"capabilityAuthorPending":        {"g0/o0!no-aggregating-item", 0, 0},
	"capabilityEphemeral":            {"g3/o9[op,task,tgt;op2,report,task2,tgt2;op3,role,task3,tgt3]", 3, 3},
	"capabilityProposals":            {"g0/o0!no-aggregating-item", 0, 0},
	"capabilityRead":                 {"g0/o0!no-aggregating-item", 0, 0},
	"capabilityReadGrants":           {"g0/o0!no-aggregating-item", 0, 0},
	"capabilityReadWildcardGrants":   {"g0/o0!no-aggregating-item", 0, 0},
	"capabilityRoleIndex":            {"g0/o0!no-aggregating-item", 0, 0},
	"capabilityRoles":                {"g1/o1[perm,role]", 1, 1},
	"capabilityServiceAccess":        {"g1/o1[loc,loc0,svc]", 1, 1},
	"clauseSatisfaction":             {"g4/o4!multiplicity-sensitive-aggregator g0/o0!no-aggregating-item", 0, 4},
	"clinicAppointments":             {"g3/o3!no-aggregating-item", 0, 3},
	"clinicAppointmentsRead":         {"g3/o3!no-aggregating-item", 0, 3},
	"clinicEncountersRead":           {"g1/o1!no-aggregating-item", 0, 1},
	"clinicIdentitiesRead":           {"g0/o0!no-aggregating-item", 0, 0},
	"clinicLedgerHistory":            {"g1/o1!no-aggregating-item", 0, 1},
	"clinicNoShowSettlement":         {"g2/o3[credit,tx] g0/o0!no-aggregating-item", 1, 2},
	"clinicPatientAccounts":          {"g1/o1!no-aggregating-item", 0, 1},
	"clinicPatientReadGrants":        {"g0/o0!no-aggregating-item", 0, 0},
	"clinicPatients":                 {"g0/o0!no-aggregating-item", 0, 0},
	"clinicPatientsRead":             {"g2/o4[a,b,b2,pr] g0/o0!no-aggregating-item", 1, 2},
	"clinicProviderReadGrants":       {"g0/o0!no-aggregating-item", 0, 0},
	"clinicProviders":                {"g1/o1!no-aggregating-item", 0, 1},
	"clinicSiteBackfill":             {"g1/o1!no-aggregating-item", 0, 1},
	"clinicSites":                    {"g0/o0!no-aggregating-item", 0, 0},
	"consoleOperatorReadGrants":      {"g0/o0!no-aggregating-item", 0, 0},
	"demoOperatorReadGrants":         {"g0/o0!no-aggregating-item", 0, 0},
	"duplicateCandidates":            {"g0/o0!no-aggregating-item", 0, 0},
	"edgeCatalog#0":                  {"g1/o3!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeCatalog#1":                  {"g1/o2!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeCatalog#2":                  {"g1/o2!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeEntityBookings":             {"g1/o4!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeEntityMenuItems":            {"g1/o2!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeEntityProviders":            {"g1/o2!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeEntitySessions#0":           {"g1/o5!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeEntitySessions#1":           {"g1/o3!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeEntityStudios":              {"g1/o2!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeEntityTabs":                 {"g1/o3!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeIdentity":                   {"g8/o10[container,loc;instr;leaseapp;pat;prov;role;sp;work,workContainer]", 8, 8},
	"edgeInstances":                  {"g1/o2!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeManifestProviderReadGrants": {"g1/o1[instr,sess] g1/o1[appt,pr] g1/o1[inst,sp,tpl] g0/o0!no-aggregating-item", 3, 1},
	"edgeManifestReadGrants":         {"g1/o2[container,home,tpl] g1/o3[container,home,op,tpl] g1/o2[op,task] g1/o1[task] g1/o1[inst] g1/o3[container,home,sess,studio] g1/o2[container,home,prov] g1/o1[bk] g1/o2[la,tab] g1/o2[container,home,item] g0/o0!no-aggregating-item", 10, 1},
	"edgeManifestStaffReadGrants":    {"g1/o2[op,perm,role] g1/o2[role,task] g1/o2[place,studio,work] g1/o2[pane,role] g1/o2[place,wo,work] g0/o0!no-aggregating-item", 5, 1},
	"edgeProviderQueue":              {"g1/o1!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeProviderSchedule":           {"g1/o1!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeServices":                   {"g1/o4!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeStaffPanes":                 {"g1/o2!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeStaffWorkOrders":            {"g1/o2!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeTasks#0":                    {"g1/o5!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"edgeTasks#1":                    {"g1/o6!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"followUpReminders":              {"g2/o2!no-aggregating-item", 0, 2},
	"frontDeskBookingHistory":        {"g1/o1!no-aggregating-item", 0, 1},
	"frontDeskBookings":              {"g1/o1!no-aggregating-item", 0, 1},
	"frontDeskLeaseDetails":          {"g1/o1!no-aggregating-item", 0, 1},
	"frontDeskVisits":                {"g0/o0!no-aggregating-item", 0, 0},
	"applicantOnboarding":            {"g2/o4[app,u;onbOp,onbTask] g0/o0!no-aggregating-item", 2, 2},
	"identityAnchors":                {"g4/o7[bound;container,loc;managed,managedContainer;work,workContainer]", 4, 4},
	"identityCredentialBindingsRead": {"g0/o0!no-aggregating-item", 0, 0},
	"identityCredentialsRead":        {"g0/o0!no-aggregating-item", 0, 0},
	"identityErasureResidue":         {"g1/o1[c] g1/o1[o] g1/o1[x] g1/o1[dout] g1/o1[din] g0/o0!no-aggregating-item", 5, 1},
	"identityIndexHint":              {"g0/o0!no-aggregating-item", 0, 0},
	"landlordLeaseApplicationsRead":  {"g1/o1[inst] g0/o0!no-aggregating-item", 1, 1},
	"landlordUnitsRead":              {"g0/o0!no-aggregating-item", 0, 0},
	"leaseAccounts":                  {"g1/o1!no-aggregating-item", 0, 1},
	"leaseApplicationComplete":       {"g5/o10[docInst;inst;leaseDocObj;mgr;onbOp,onbTask;sigOp,sigTask] g0/o0!no-aggregating-item", 6, 5},
	"leaseApplicationsRead":          {"g5/o5[inst;prop] g0/o0!no-aggregating-item", 2, 5},
	"leaseExpiry":                    {"g2/o3[landlord;rn] g0/o0!no-aggregating-item", 2, 2},
	"leaseRentSettlement":            {"g1/o1[c] g0/o0!no-aggregating-item", 1, 1},
	"ledgerHistory":                  {"g1/o1!no-aggregating-item", 0, 1},
	"menuCatalog":                    {"g1/o1!no-aggregating-item", 0, 1},
	"myTasks":                        {"g2/o6[op,task,tgt;qop,qtask,qtgt,role]", 2, 2},
	"objectAttachments":              {"g1/o1[owner,r] g0/o0!no-aggregating-item", 1, 1},
	"objectIdentityAttachmentsRead":  {"g0/o0!no-aggregating-item", 0, 0},
	"objectLiveness":                 {"g0/o0!no-aggregating-item g0/o0!no-aggregating-item", 0, 0}, // No aggregating item in either stage.
	"oneBillCafeEntries":             {"g0/o0!no-aggregating-item", 0, 0},
	"oneBillClinicEntries":           {"g0/o0!no-aggregating-item", 0, 0},
	"oneBillRentEntries":             {"g0/o0!no-aggregating-item", 0, 0},
	"oneBillWellnessEntries":         {"g0/o0!no-aggregating-item", 0, 0},
	"opCatalog":                      {"g1/o1[perm,role]", 1, 1},
	"orphanedTaskGrants":             {"g1/o1!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"pastDueAppointments":            {"g2/o2!no-aggregating-item", 0, 2},
	"pastDueBookings":                {"g2/o2!no-aggregating-item", 0, 2},
	"patientIdentityReadGrants":      {"g0/o0!no-aggregating-item", 0, 0},
	"piiKeyEnvelope":                 {"g0/o0!no-aggregating-item", 0, 0},
	"providerAppointmentsRead":       {"g2/o3!no-aggregating-item", 0, 2},
	"providerIdentityReadGrants":     {"g0/o0!no-aggregating-item", 0, 0},
	"providerSites":                  {"g0/o0!no-aggregating-item", 0, 0},
	"renewalComplete":                {"g1/o5[inst;landlord,u] g0/o0!no-aggregating-item", 2, 1},
	"renewalsRead":                   {"g0/o0!no-aggregating-item g0/o0!no-aggregating-item", 0, 0},
	"retentionKeyStatus":             {"g0/o0!no-aggregating-item", 0, 0},
	"shredStatus":                    {"g0/o0!no-aggregating-item", 0, 0},
	"staffReadGrants":                {"g0/o0!no-aggregating-item", 0, 0},
	"staleAssignedTasks":             {"g0/o0!no-aggregating-item", 0, 0},
	// Four sibling OPTIONAL MATCHes off the anchor (op, onbIdentity, sigApp,
	// termsRenewal), none of them aggregating anything — the stage's branch
	// product IS the intended one-row-per-task output, so §4.2 refuses to fold
	// it (no-aggregating-item), same shape as orphanedTaskGrants' own single
	// forOperation branch.
	"staleUserTasks":                    {"g4/o4!no-aggregating-item g0/o0!no-aggregating-item", 0, 4},
	"unroutedTasks":                     {"g0/o0!no-aggregating-item", 0, 0},
	"visitSeriesDue":                    {"g2/o2!no-aggregating-item", 0, 2},
	"visitSeriesRead":                   {"g3/o3!no-aggregating-item", 0, 3},
	"visitSeriesSiteBackfill":           {"g2/o2!no-aggregating-item", 0, 2},
	"wellnessBookingReminders":          {"g2/o2!no-aggregating-item", 0, 2},
	"wellnessBookings":                  {"g2/o3!no-aggregating-item", 0, 2},
	"wellnessClassPriceSettlement":      {"g2/o2!multiplicity-sensitive-aggregator g0/o0!no-aggregating-item", 0, 2},
	"wellnessIdentitiesRead":            {"g0/o0!no-aggregating-item", 0, 0},
	"wellnessInstructors":               {"g1/o1!no-aggregating-item", 0, 1},
	"wellnessLedgerHistory":             {"g3/o3!no-aggregating-item", 0, 3},
	"wellnessMemberAccounts":            {"g0/o0!no-aggregating-item g1/o1!no-aggregating-item", 0, 1},
	"wellnessMembers":                   {"g0/o0!no-aggregating-item", 0, 0},
	"wellnessNoShowSettlement":          {"g2/o2!multiplicity-sensitive-aggregator g0/o0!no-aggregating-item", 0, 2},
	"wellnessOrphanedBookingSettlement": {"g1/o1!no-aggregating-item g0/o0!no-aggregating-item", 0, 1},
	"wellnessRefundSettlement":          {"g1/o1!multiplicity-sensitive-aggregator g0/o0!no-aggregating-item", 0, 1},
	"wellnessSessions":                  {"g2/o2!no-aggregating-item", 0, 2},
	"wellnessStudios":                   {"g0/o0!no-aggregating-item", 0, 0},
}

// decomposingCorpusLenses is the population whose sibling branches the executor
// now evaluates apart.
//
// Every name here is executed under BOTH configurations by a differential in
// ruleengine/full — the sixteen hand-authored lenses by
// TestBranchDecomposition_ShippedLensesProjectIdenticalRows and its randomized
// sibling, the three generated read-grant producers by
// TestBranchDecomposition_GeneratedProducersProjectIdenticalRows. That coverage
// is not left to this comment: TestBranchDecomposition_EveryDecomposingCorpusLens
// ReachesADifferential asserts the two enumerations agree, because the first
// version of this sentence was true of nine of the seventeen.
var decomposingCorpusLenses = []string{
	"applicantOnboarding",
	"capabilityEphemeral",
	"capabilityRoles",
	"capabilityServiceAccess",
	"clinicNoShowSettlement",
	"clinicPatientsRead",
	"edgeIdentity",
	"edgeManifestProviderReadGrants",
	"edgeManifestReadGrants",
	"edgeManifestStaffReadGrants",
	"identityAnchors",
	"identityErasureResidue",
	"landlordLeaseApplicationsRead",
	"leaseApplicationComplete",
	"leaseApplicationsRead",
	"leaseExpiry",
	"leaseRentSettlement",
	"myTasks",
	"objectAttachments",
	"opCatalog",
	"renewalComplete",
}

// siblingBranchGroupLenses is the design's §2 claim made executable: the lenses
// holding two or more SIBLING branch groups in one stage. The design said
// FOURTEEN by eye and the fire brief's coarse scan bounded it above at
// thirty-two clause-counted literals; the analysis derives TWENTY-SIX.
var siblingBranchGroupLenses = []string{
	"applicantOnboarding",
	"appointmentReminders",
	"cafeTabSettlement",
	"capabilityEphemeral",
	"clauseSatisfaction",
	"clinicAppointments",
	"clinicAppointmentsRead",
	"clinicNoShowSettlement",
	"clinicPatientsRead",
	"edgeIdentity",
	"followUpReminders",
	"identityAnchors",
	"leaseApplicationComplete",
	"leaseApplicationsRead",
	"leaseExpiry",
	"myTasks",
	"pastDueAppointments",
	"pastDueBookings",
	"providerAppointmentsRead",
	"staleUserTasks",
	"visitSeriesDue",
	"visitSeriesRead",
	"visitSeriesSiteBackfill",
	"wellnessBookingReminders",
	"wellnessBookings",
	"wellnessClassPriceSettlement",
	"wellnessLedgerHistory",
	"wellnessNoShowSettlement",
	"wellnessSessions",
}

// multiGroupDecomposingLenses is the intersection — wide AND foldable. The
// other wide lenses are refused: most because their stage aggregates nothing at
// all, so the branch product IS the intended row count there, and the rest by
// §4.2's non-DISTINCT collect/count, clauseSatisfaction included.
var multiGroupDecomposingLenses = []string{
	"applicantOnboarding",
	"capabilityEphemeral",
	"clinicNoShowSettlement",
	"clinicPatientsRead",
	"edgeIdentity",
	"identityAnchors",
	"leaseApplicationComplete",
	"leaseApplicationsRead",
	"leaseExpiry",
	"myTasks",
}

// footprintValidationVerdicts pins every actorAggregate lens's
// §13.3 footprint-validation verdict — the classifier that reads the compiled
// AST rather than anything the executor materializes, so decomposition must
// leave every one of them exactly where it found it.
var footprintValidationVerdicts = map[string]bool{
	"applicantOnboarding":               true,
	"appointmentReminders":              true,
	"augurDispatchPending":              false,
	"backgroundCheckFreshness":          false,
	"cafeStaleTabSettlement":            false,
	"cafeTabSettlement":                 true,
	"capability":                        false,
	"capabilityAuthorPending":           false,
	"capabilityEphemeral":               true,
	"capabilityRead":                    false,
	"capabilityRoles":                   false,
	"capabilityServiceAccess":           true,
	"clauseSatisfaction":                true,
	"clinicNoShowSettlement":            true,
	"clinicSiteBackfill":                true,
	"edgeManifestProviderReadGrants":    false,
	"edgeManifestReadGrants":            false,
	"edgeManifestStaffReadGrants":       false,
	"followUpReminders":                 true,
	"identityAnchors":                   true,
	"identityErasureResidue":            true,
	"leaseApplicationComplete":          true,
	"leaseExpiry":                       true,
	"leaseRentSettlement":               true,
	"myTasks":                           true,
	"objectAttachments":                 true,
	"objectLiveness":                    false,
	"orphanedTaskGrants":                true,
	"pastDueAppointments":               true,
	"pastDueBookings":                   true,
	"renewalComplete":                   true,
	"staleAssignedTasks":                true,
	"staleUserTasks":                    true,
	"unroutedTasks":                     true,
	"visitSeriesDue":                    true,
	"visitSeriesSiteBackfill":           true,
	"wellnessBookingReminders":          true,
	"wellnessClassPriceSettlement":      true,
	"wellnessNoShowSettlement":          true,
	"wellnessOrphanedBookingSettlement": true,
	"wellnessRefundSettlement":          true,
}
