package main

import (
	"errors"
	"io"
	"net/http"
	"strconv"
	"strings"

	"github.com/operatinggraph/lattice/internal/bootstrap"
	"github.com/operatinggraph/lattice/internal/substrate"
)

// handleLeaseDocument routes /api/lease-document — the executed-lease artifact
// for a signed application:
//
//	GET /api/lease-document?leaseAppKey= → stream the anchored lease document
//
// The document is generated by the platform's external docGen vendor (bridge
// adapter) the moment an application is signed and anchored to the leaseapp by
// Weaver's AttachObject dispatch (the lease-signing missing_leaseDoc /
// missing_leaseDocAttach convergence chain) — the app submits no operation and
// renders nothing; it only DISPLAYS the attached artifact's bytes.
func (s *server) handleLeaseDocument(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		s.handleLeaseDocumentGet(w, r)
	default:
		s.writeError(w, http.StatusMethodNotAllowed,
			"expected GET /api/lease-document?leaseAppKey=")
	}
}

// handleLeaseDocumentGet streams the anchored executed-lease bytes for
// download, served as an AUTHENTICATED actor off the PROTECTED, RLS-scoped
// read_lease_applications model (the same read boundary handleApplications
// uses): a missing/invalid bearer token is 401, and RLS scopes the row to the
// applicant themself — a leaseAppKey that isn't the caller's returns the same
// 404 as a genuinely absent one, so the caller cannot tell "not mine" from
// "not real."
//
// The row's doc_store_name / doc_filename / doc_content_type columns carry the
// anchored artifact's pointers (projected only once the signedLease attachment
// exists). A signed application whose document has not yet converged answers
// 404 "being generated" — the honest async answer; the bytes stream from the
// core-objects store (ObjectGet — NATS verifies the digest as it streams; the
// Refractor is never in the byte path).
func (s *server) handleLeaseDocumentGet(w http.ResponseWriter, r *http.Request) {
	actor, err := s.authenticateRead(r)
	if err != nil {
		s.writeError(w, http.StatusUnauthorized, "authentication required: "+err.Error())
		return
	}
	leaseAppKey := strings.TrimSpace(r.URL.Query().Get("leaseAppKey"))
	if leaseAppKey == "" {
		s.writeError(w, http.StatusBadRequest, "leaseAppKey query param is required")
		return
	}
	if s.pgPool == nil {
		s.writeError(w, http.StatusBadGateway,
			"protected read model not configured (set LOFTSPACE_APP_PG_DSN and ensure Postgres + the lease-signing protected lens are up)")
		return
	}

	ctx, cancel := s.reqContext(r)
	defer cancel()

	notFoundMsg := "no application " + shortKeyServer(leaseAppKey) +
		" in the read model (is lease-signing installed and projecting, and are you the applicant?)"
	row, ok, err := queryApplicationByKey(ctx, s.pgPool, actor.Subject, leaseAppKey)
	if err != nil {
		s.logger.Error("read protected lease application for document", "error", err)
		s.writeError(w, http.StatusBadGateway, "could not read the protected lease-applications model")
		return
	}
	if !ok {
		s.writeError(w, http.StatusNotFound, notFoundMsg)
		return
	}

	storeName := strDeref(row.DocStoreName)
	if storeName == "" {
		// The artifact has not anchored yet. A signed application is inside the
		// convergence window (the docGen vendor + Weaver attach are in flight) —
		// the honest async answer; anything else has no document to serve.
		if strings.TrimSpace(strDeref(row.SignedAt)) != "" {
			s.writeError(w, http.StatusNotFound,
				"the executed lease document is being generated — try again shortly")
			return
		}
		s.writeError(w, http.StatusNotFound, notFoundMsg)
		return
	}

	conn, ok := s.requireConn(w)
	if !ok {
		return
	}
	rc, info, err := conn.ObjectGet(ctx, bootstrap.CoreObjectsBucket, storeName)
	if err != nil {
		if errors.Is(err, substrate.ErrObjectNotFound) {
			s.writeError(w, http.StatusNotFound, "lease document bytes not found")
			return
		}
		s.writeError(w, http.StatusBadGateway, "read lease document bytes: "+err.Error())
		return
	}
	defer rc.Close()

	contentType := strings.TrimSpace(strDeref(row.DocContentType))
	if contentType == "" {
		contentType = "text/plain; charset=utf-8"
	}
	filename := strings.TrimSpace(strDeref(row.DocFilename))
	if filename == "" {
		filename = "signed-lease-" + shortKeyServer(leaseAppKey) + ".txt"
	}
	w.Header().Set("Content-Type", contentType)
	w.Header().Set("Content-Length", strconv.FormatUint(info.Size, 10))
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("Content-Disposition", "attachment; filename=\""+filename+"\"")
	w.Header().Set("Content-Security-Policy", "default-src 'none'; sandbox")
	w.WriteHeader(http.StatusOK)
	_, _ = io.Copy(w, rc)
}

// strDeref returns "" for a nil pointer, the pointed-to value otherwise.
func strDeref(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}

// shortKeyServer abbreviates a vtx.<type>.<id> key to <type>.<id-prefix> for
// human-facing filenames / messages, mirroring the FE's shortKey.
func shortKeyServer(key string) string {
	parts := strings.Split(key, ".")
	if len(parts) >= 3 {
		id := parts[2]
		if len(id) > 8 {
			id = id[:8]
		}
		return parts[1] + "." + id
	}
	return key
}
