package main

import (
	"errors"
	"io"
	"net/http"
	"strconv"
	"strings"

	"github.com/operatinggraph/lattice/internal/bootstrap"
	"github.com/operatinggraph/lattice/internal/substrate"
)

// handleLeaseDocument routes /api/lease-document — the executed-lease artifact
// for a signed application:
//
//	GET /api/lease-document?leaseAppKey= → stream the anchored lease document
//
// The document is generated by the platform's external docGen vendor (bridge
// adapter) the moment an application is signed and anchored to the leaseapp by
// Weaver's AttachObject dispatch (the lease-signing missing_leaseDoc /
// missing_leaseDocAttach convergence chain) — the app submits no operation and
// renders nothing; it only DISPLAYS the attached artifact's bytes.
func (s *server) handleLeaseDocument(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		s.handleLeaseDocumentGet(w, r)
	default:
		s.writeError(w, http.StatusMethodNotAllowed,
			"expected GET /api/lease-document?leaseAppKey=")
	}
}

// leaseDocumentRow is the narrow shape handleLeaseDocumentGet needs off
// either the applicant-scoped or the landlord-scoped protected row: whether
// the landlord has approved, whether the application is signed, and the
// anchored artifact's pointers. Both protectedApplicationRow and
// protectedLandlordRow carry these under the same names; this lets the two
// scopes share one gate + stream path.
type leaseDocumentRow struct {
	landlordApproved bool
	signedAt         string
	storeName        string
	filename         string
	contentType      string
}

// handleLeaseDocumentGet streams the anchored executed-lease bytes for
// download, served as an AUTHENTICATED actor off the PROTECTED, RLS-scoped
// read models: a missing/invalid bearer token is 401. It tries the
// applicant-scoped read_lease_applications row first (the same read boundary
// handleApplications uses); when that finds no row it falls back to the
// LANDLORD-scoped read_landlord_lease_applications row under the SAME actor
// (the managing landlord is a party to the lease too; that lens also anchors
// on the unit's building, so a building-anchored staffer reads it exactly as
// they read the application row itself) — RLS does the
// authorization on both reads, and this handler adds no key-based check of
// its own. A leaseAppKey that is neither the caller's application nor one
// they manage returns the same 404 as a genuinely absent one, so the caller
// cannot tell "not mine" from "not real."
//
// The approval gate comes before the document gate: a DECLINED application
// and a SIGNED-BUT-UNDECIDED one both answer 404 "not approved" — sign
// precedes decide by design, so a document minted before any decision exists
// must never be served past a non-approval. Only once the landlord has
// approved does the doc_store_name / doc_filename / doc_content_type pointer
// presence matter: null there (a signed, approved application still inside
// the docGen+attach convergence window) answers 404 "being generated," the
// honest async answer. The bytes stream from the core-objects store
// (ObjectGet — NATS verifies the digest as it streams; the Refractor is
// never in the byte path).
func (s *server) handleLeaseDocumentGet(w http.ResponseWriter, r *http.Request) {
	actor, err := s.authenticateRead(r)
	if err != nil {
		s.writeError(w, http.StatusUnauthorized, "authentication required: "+err.Error())
		return
	}
	leaseAppKey := strings.TrimSpace(r.URL.Query().Get("leaseAppKey"))
	if leaseAppKey == "" {
		s.writeError(w, http.StatusBadRequest, "leaseAppKey query param is required")
		return
	}
	if s.pgPool == nil {
		s.writeError(w, http.StatusBadGateway,
			"protected read model not configured (set LOFTSPACE_APP_PG_DSN and ensure Postgres + the lease-signing protected lens are up)")
		return
	}

	ctx, cancel := s.reqContext(r)
	defer cancel()

	notFoundMsg := "no application " + shortKeyServer(leaseAppKey) +
		" in the read model (is lease-signing installed and projecting, and are you the applicant or the managing landlord?)"

	appRow, ok, err := queryApplicationByKey(ctx, s.pgPool, actor.Subject, leaseAppKey)
	if err != nil {
		s.logger.Error("read protected lease application for document", "error", err)
		s.writeError(w, http.StatusBadGateway, "could not read the protected lease-applications model")
		return
	}

	var doc leaseDocumentRow
	if ok {
		doc = leaseDocumentRow{
			landlordApproved: appRow.LandlordApproved,
			signedAt:         strDeref(appRow.SignedAt),
			storeName:        strDeref(appRow.DocStoreName),
			filename:         strDeref(appRow.DocFilename),
			contentType:      strDeref(appRow.DocContentType),
		}
	} else {
		landlordRow, lok, err := queryLandlordApplicationByKey(ctx, s.pgPool, actor.Subject, leaseAppKey)
		if err != nil {
			s.logger.Error("read protected landlord lease application for document", "error", err)
			s.writeError(w, http.StatusBadGateway, "could not read the protected landlord lease-applications model")
			return
		}
		if !lok {
			s.writeError(w, http.StatusNotFound, notFoundMsg)
			return
		}
		doc = leaseDocumentRow{
			landlordApproved: landlordRow.LandlordApproved,
			signedAt:         strDeref(landlordRow.SignedAt),
			storeName:        strDeref(landlordRow.DocStoreName),
			filename:         strDeref(landlordRow.DocFilename),
			contentType:      strDeref(landlordRow.DocContentType),
		}
	}

	if !doc.landlordApproved {
		// Covers both a landlord DECLINE and a signed-but-undecided application —
		// sign precedes decide by design, so a document minted ahead of any
		// decision must never be served until the landlord actually approves.
		s.writeError(w, http.StatusNotFound, "no executed lease: the application is not approved")
		return
	}
	if doc.storeName == "" {
		// The artifact has not anchored yet. A signed, approved application is
		// inside the convergence window (the docGen vendor + Weaver attach are in
		// flight) — the honest async answer; anything else has no document to serve.
		if strings.TrimSpace(doc.signedAt) != "" {
			s.writeError(w, http.StatusNotFound,
				"the executed lease document is being generated — try again shortly")
			return
		}
		s.writeError(w, http.StatusNotFound, notFoundMsg)
		return
	}

	conn, ok := s.requireConn(w)
	if !ok {
		return
	}
	rc, info, err := conn.ObjectGet(ctx, bootstrap.CoreObjectsBucket, doc.storeName)
	if err != nil {
		if errors.Is(err, substrate.ErrObjectNotFound) {
			s.writeError(w, http.StatusNotFound, "lease document bytes not found")
			return
		}
		s.writeError(w, http.StatusBadGateway, "read lease document bytes: "+err.Error())
		return
	}
	defer rc.Close()

	contentType := strings.TrimSpace(doc.contentType)
	if contentType == "" {
		contentType = "text/plain; charset=utf-8"
	}
	filename := strings.TrimSpace(doc.filename)
	if filename == "" {
		filename = "signed-lease-" + shortKeyServer(leaseAppKey) + ".txt"
	}
	w.Header().Set("Content-Type", contentType)
	w.Header().Set("Content-Length", strconv.FormatUint(info.Size, 10))
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("Content-Disposition", "attachment; filename=\""+filename+"\"")
	w.Header().Set("Content-Security-Policy", "default-src 'none'; sandbox")
	w.WriteHeader(http.StatusOK)
	_, _ = io.Copy(w, rc)
}

// strDeref returns "" for a nil pointer, the pointed-to value otherwise.
func strDeref(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}

// shortKeyServer abbreviates a vtx.<type>.<id> key to <type>.<id-prefix> for
// human-facing filenames / messages, mirroring the FE's shortKey.
func shortKeyServer(key string) string {
	parts := strings.Split(key, ".")
	if len(parts) >= 3 {
		id := parts[2]
		if len(id) > 8 {
			id = id[:8]
		}
		return parts[1] + "." + id
	}
	return key
}
