package pipeline

import (
	"context"
	"fmt"
	"sort"

	"github.com/operatinggraph/lattice/internal/refractor/ruleengine"
	"github.com/operatinggraph/lattice/internal/refractor/ruleengine/full"
)

// walkOwnedColumns classifies a multi-walk Personal lens's compiled branches
// via full.ClassifyBranchReturnColumns and returns the RETURN column aliases
// proved ColumnWalkOwned. Returns nil (not an error) when any branch isn't a
// *full.CompiledRule or classification fails — mergeRowGroup's caller-side
// fallback is the pre-existing strict behavior, so a nil map never relaxes
// anything it didn't before. Classification failing here would mean the lens
// installed despite corekv_source.go running this same check at install time
// (Lattice's authoritative gate), so this is defense in depth, not the
// primary enforcement point.
//
// This call site is what makes ClassifyBranchReturnColumns' classification
// runtime load-bearing: a ColumnWalkOwned verdict now decides whether a
// disagreement is resolved deterministically (mergeRowGroup) instead of
// refused. Before this fire the same classification was install-time-only
// (corekv_source.go), where a wrong verdict could only make the install gate
// too permissive or too strict — never change what a running lens projects.
// The classifier's own known blind spots (it reads only branch 0's RETURN
// expressions to derive every branch's alias-to-ownership mapping, and a
// pattern-comprehension-local variable name that happens to collide with a
// walk's own bound variable is treated as that walk's, not the
// comprehension's) are inert today only because every real multi-walk spec
// is generated by pkgmgr's composeDataLensSpec (a byte-identical tail across
// every Walk, no per-branch aliasing, no comprehension/chain-variable
// collisions) — a hand-authored CypherBranches spec that violated either
// assumption would now silently pick a value where it used to fail closed.
func walkOwnedColumns(branches []ruleengine.CompiledRule) map[string]int {
	fullBranches := make([]*full.CompiledRule, len(branches))
	for i, b := range branches {
		fb, ok := b.(*full.CompiledRule)
		if !ok {
			return nil
		}
		fullBranches[i] = fb
	}
	plan, err := full.ClassifyBranchReturnColumns(fullBranches)
	if err != nil {
		return nil
	}
	owned := make(map[string]int, len(plan))
	for _, col := range plan {
		if col.Ownership == full.ColumnWalkOwned {
			owned[col.Alias] = col.OwnerBranch
		}
	}
	return owned
}

// executeBranches runs this pipeline's compiled rule(s) for one actor: a
// single ExecuteWithFootprint call for an ordinary lens, or one independent
// call per branch — merged by output key, footprints unioned — for a
// multi-walk Personal lens (refractor-shared-keyspace-arbitration-
// design.md §13.2). Factored out of executeFullForActorOnce so the single-
// branch path stays exactly what it was before branch merging existed.
//
// seedAnchor rides the EventContext into the single-branch call only. A
// multi-walk lens never receives one — seedAnchorFor's eligibility excludes it
// (seedAnchorLabels is cleared for multi-walk installs, and a Personal lens
// carries an ActorEnumerator besides) — so the branch loop passes the unseeded
// context and every branch builds its own anchor candidate set by scan.
func (p *Pipeline) executeBranches(
	ctx context.Context, rs ruleState, actorKey string, nodeProps map[string]any, params map[string]any, seedAnchor string,
) ([]ruleengine.ProjectionResult, ruleengine.EvalFootprint, error) {
	ec := ruleengine.EventContext{NodeKey: actorKey, NodeProps: nodeProps, Parameters: params}
	if len(rs.branches) <= 1 {
		ec.SeedAnchor = seedAnchor
		return rs.engine.ExecuteWithFootprint(ctx, rs.cr, ec, p.adjKV, p.coreKV)
	}

	branchOuts := make([][]ruleengine.ProjectionResult, len(rs.branches))
	footprints := make([]ruleengine.EvalFootprint, len(rs.branches))
	for i, cr := range rs.branches {
		out, fp, err := rs.engine.ExecuteWithFootprint(ctx, cr, ec, p.adjKV, p.coreKV)
		if err != nil {
			return nil, ruleengine.EvalFootprint{}, fmt.Errorf("pipeline: branch %d: %w", i, err)
		}
		branchOuts[i] = out
		footprints[i] = fp
	}
	merged, err := mergeBranchRows(branchOuts, rs.walkOwnedColumns)
	if err != nil {
		return nil, ruleengine.EvalFootprint{}, err
	}
	return merged, mergeFootprints(footprints), nil
}

// mergeBranchRows merges the row sets N independently-evaluated branches of
// a multi-walk Personal lens produced for one actor
// (refractor-shared-keyspace-arbitration-design.md §13.2), keyed by output
// Key. A key appearing in only one branch passes through unchanged — every
// RETURN column a sibling walk owns is already null in that branch by
// construction (pkgmgr's composeDataLensSpec doc comment). A key appearing
// in 2+ branches is merged column-by-column: no non-null value anywhere
// stays the merged value's null; exactly one distinct non-null value across
// the sharing rows is taken as-is (a walk-owned column, or every branch's
// identical anchor-derived computation); two or more DISTINCT non-null
// values on an anchor-derived column is the real defect §13.3's
// expansion-time classifier exists to keep out of a shipped lens, and the
// merge fails loudly rather than picking a winner. The same disagreement on
// a walkOwned (ColumnWalkOwned) column is a different situation — it can
// only mean the one branch that owns the column matched it more than once
// for this anchor (e.g. a multi-hat actor reaching one op via 2+ roles) — so
// mergeRowGroup resolves it deterministically instead of failing.
func mergeBranchRows(branchOuts [][]ruleengine.ProjectionResult, walkOwned map[string]int) ([]ruleengine.ProjectionResult, error) {
	type group struct {
		rows []ruleengine.ProjectionResult
	}
	byKey := map[string]*group{}
	order := make([]string, 0)
	for _, branch := range branchOuts {
		for _, row := range branch {
			k := serializeRowKey(row.Key)
			g, ok := byKey[k]
			if !ok {
				g = &group{}
				byKey[k] = g
				order = append(order, k)
			}
			g.rows = append(g.rows, row)
		}
	}

	merged := make([]ruleengine.ProjectionResult, 0, len(order))
	for _, k := range order {
		rows := byKey[k].rows
		if len(rows) == 1 {
			merged = append(merged, rows[0])
			continue
		}
		row, err := mergeRowGroup(rows, walkOwned)
		if err != nil {
			return nil, err
		}
		merged = append(merged, row)
	}
	return merged, nil
}

// mergeRowGroup combines 2+ branches' rows sharing one output key into one
// row. Delete wins if any branch marked the key deleted — conservative: a
// walk that no longer reaches this anchor should not resurrect a row a
// sibling walk's branch is retracting. Key is taken from the group (every
// row's Key is identical by construction — it is what grouped them).
func mergeRowGroup(rows []ruleengine.ProjectionResult, walkOwned map[string]int) (ruleengine.ProjectionResult, error) {
	out := ruleengine.ProjectionResult{Key: rows[0].Key}
	for _, r := range rows {
		if r.Delete {
			out.Delete = true
		}
	}
	if out.Delete {
		return out, nil
	}

	// Walk-owned columns are resolved per OWNER BRANCH, as a unit, before the
	// column-by-column pass below ever sees them — never picked independently
	// per column, and never coupled across owners. Two walk-owned columns
	// computed from the SAME owner branch's match (e.g. viaRole/viaRoleName
	// both derived from one role-walk's `role` binding) are correlated: an
	// independent per-column pick could combine one row's viaRole with a
	// DIFFERENT row's viaRoleName, fabricating a {key, name} pair that never
	// coexisted in any real evaluation. Columns owned by DIFFERENT branches
	// are independent of each other (each can only ever be populated by its
	// own branch's own match) and must be resolved separately — coupling them
	// into one shared pick would let one owner's winning row's null for the
	// OTHER owner's column silently overwrite that owner's real value.
	byOwner := map[int][]string{}
	for col, owner := range walkOwned {
		byOwner[owner] = append(byOwner[owner], col)
	}

	values := map[string]any{}
	seen := map[string]bool{}
	for _, r := range rows {
		for col, v := range r.Values {
			if _, ok := walkOwned[col]; ok {
				continue
			}
			if !seen[col] {
				seen[col] = true
				values[col] = v
				continue
			}
			existing := values[col]
			if v == nil || existing == nil {
				if existing == nil {
					values[col] = v
				}
				continue
			}
			if valuesEqual(existing, v) {
				continue
			}
			return ruleengine.ProjectionResult{}, fmt.Errorf(
				"pipeline: branch merge: column %q disagrees across walks for key %v: %v vs %v — "+
					"an anchor-derived column must compute identically in every branch "+
					"(refractor-shared-keyspace-arbitration-design.md §13.2/§13.3)",
				col, rows[0].Key, existing, v)
		}
	}

	// Only rows carrying at least one non-null value among THIS owner's own
	// columns are candidates — a row from a branch that doesn't own them is
	// never null-by-accident (§13.2's "null by construction"), so it never
	// competes for the pick. The tie-break itself is presentation-only
	// stability (§13.2's own framing), not a real ordering.
	for _, cols := range byOwner {
		sorted := append([]string(nil), cols...)
		sort.Strings(sorted)

		var winner *ruleengine.ProjectionResult
		var winnerEnc string
		for i := range rows {
			enc, hasValue := encodeColumnValues(rows[i].Values, sorted)
			if !hasValue {
				continue
			}
			if winner == nil || enc < winnerEnc {
				winner, winnerEnc = &rows[i], enc
			}
		}
		for _, col := range cols {
			if winner != nil {
				values[col] = winner.Values[col]
			} else {
				values[col] = nil
			}
		}
	}
	out.Values = values
	return out, nil
}

func valuesEqual(a, b any) bool {
	return fmt.Sprintf("%v", a) == fmt.Sprintf("%v", b)
}

// encodeColumnValues builds one stable encoding of the given columns' values
// in this row, and reports whether any of them is non-null. cols must
// already be sorted (the caller sorts once per owner group, not per row) so
// two rows with identical values for these columns encode identically
// regardless of map iteration order — what makes mergeRowGroup's pick
// reproducible run to run.
func encodeColumnValues(rowValues map[string]any, cols []string) (string, bool) {
	if len(cols) == 0 {
		return "", false
	}
	hasValue := false
	enc := ""
	for _, col := range cols {
		v := rowValues[col]
		if v != nil {
			hasValue = true
		}
		enc += col + "=" + fmt.Sprintf("%v", v) + "\x1f"
	}
	return enc, hasValue
}

func serializeRowKey(key map[string]any) string {
	names := make([]string, 0, len(key))
	for k := range key {
		names = append(names, k)
	}
	sort.Strings(names)
	s := ""
	for _, n := range names {
		s += n + "=" + fmt.Sprintf("%v", key[n]) + "\x1f"
	}
	return s
}

// mergeFootprints unions N branches' read-surface footprints into one
// certificate — a validating caller must catch drift on ANY key any branch
// depended on, not just branch 0's.
func mergeFootprints(footprints []ruleengine.EvalFootprint) ruleengine.EvalFootprint {
	out := ruleengine.EvalFootprint{
		NodeRevisions: map[string]uint64{},
		EdgeRevisions: map[string]uint64{},
		EdgeSelectors: map[string]ruleengine.EdgeSelectorFootprint{},
	}
	for _, fp := range footprints {
		for k, v := range fp.NodeRevisions {
			out.NodeRevisions[k] = v
		}
		for k, v := range fp.EdgeRevisions {
			out.EdgeRevisions[k] = v
		}
		for k, v := range fp.EdgeSelectors {
			existing, ok := out.EdgeSelectors[k]
			if !ok {
				existing = ruleengine.EdgeSelectorFootprint{Matched: map[ruleengine.EdgeSelector]map[string]struct{}{}}
			}
			if v.Fallback {
				existing.Fallback = true
			}
			for sel, ids := range v.Matched {
				m, ok := existing.Matched[sel]
				if !ok {
					m = map[string]struct{}{}
					existing.Matched[sel] = m
				}
				for id := range ids {
					m[id] = struct{}{}
				}
			}
			out.EdgeSelectors[k] = existing
		}
	}
	return out
}
